In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv('/content/salary.csv')

In [ ]:
df

    YearsExperience  Salary
0               1.1   39343
1               1.3   46205
2               1.5   37731
3               2.0   43525
4               2.2   39891
5               2.9   56642
6               3.0   60150
7               3.2   54445
8               3.2   64445
9               3.7   57189
10              3.9   63218
11              4.0   55794
12              4.0   56957
13              4.1   57081
14              NaN   61111
15              4.9   67938
16              5.1   66029
17              5.3   83088
18              5.9   81363
19              6.0   93940
20              6.8   91738
21              7.1   98273
22              7.9  101302
23              8.2  113812
24              8.7  109431
25              9.0  105582
26              NaN  116969
27              9.6  112635
28             10.3  122391
29             10.5  121872

In [ ]:
df.isnull().sum().sum()

np.int64(0)

In [ ]:
df['YearsExperience']=df['YearsExperience'].fillna(df['YearsExperience'].mean())

In [ ]:
df

    YearsExperience  Salary
0          1.100000   39343
1          1.300000   46205
2          1.500000   37731
3          2.000000   43525
4          2.200000   39891
5          2.900000   56642
6          3.000000   60150
7          3.200000   54445
8          3.200000   64445
9          3.700000   57189
10         3.900000   63218
11         4.000000   55794
12         4.000000   56957
13         4.100000   57081
14         5.192857   61111
15         4.900000   67938
16         5.100000   66029
17         5.300000   83088
18         5.900000   81363
19         6.000000   93940
20         6.800000   91738
21         7.100000   98273
22         7.900000  101302
23         8.200000  113812
24         8.700000  109431
25         9.000000  105582
26         5.192857  116969
27         9.600000  112635
28        10.300000  122391
29        10.500000  121872

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df[['YearsExperience']],df[['Salary']],test_size=0.2,random_state=0)

In [ ]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred=lr.predict([[12]])
y_pred

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[138005.61156525]])